-- Later verified additions beyond the 15-row embedded catalogue.
-- Keep the core registry clean: remove known stale, ambiguous, rebranded, mobile,
-- unavailable, estimate-only, or otherwise non-core candidates if they were ever staged.

DELETE FROM stress_test_locations
WHERE provider IN (
  'Independent Physicians Medical Center (IPMC)',
  'Telluride Regional Medical Center',
  'NSC Cardiology',
  'Advanced Heart and Vascular Center of New Mexico',
  'Advanced Cardiovascular Care',
  'Boulder Community Health',
  'SonoLinked',
  'UNM Exercise Physiology Lab',
  'First Coast Cardiovascular Institute',
  'Austin Cardiology Clinic',
  'South Tampa Cardiology',
  'CardioClinic',
  'Complete Cardiology Care'
);

INSERT INTO stress_test_locations (
  provider, city, state, zip, address, price, service, match_text,
  access, tier, source_url, latitude, longitude, phone, fax, email,
  footprint_note, updated_at
)
VALUES
  (
    'Cardiovascular Interventions, P.A.',
    'Orlando',
    'FL',
    '32803',
    '1900 North Mills Avenue, Suite 107, Orlando, FL 32803',
    140,
    'Regular Stress Test',
    'Direct self-pay Regular Stress Test — $140; provider stress-test lab defines the regular test as treadmill walking',
    'Self-pay cash rate; in-office treadmill stress test',
    'A',
    'https://orlandocvi.com/patient-resources/self-pay-rates-at-cvi/',
    NULL,
    NULL,
    '(407) 894-4880',
    '(407) 894-2364',
    NULL,
    'Provider self-pay page gives the $140 price and the practice stress-test lab confirms the regular test is treadmill exercise.',
    NOW()
  ),
  (
    'West Michigan Cardiology',
    'Grand Rapids',
    'MI',
    '49525',
    '3210 Eagle Run Dr NE, Grand Rapids, MI 49525',
    150,
    'Treadmill EKG Stress Test',
    'Individual screening test: Treadmill EKG Stress Test — $150',
    'Cash-pay cardiovascular screening; no insurance claim, referral, or prior authorization required',
    'A',
    'https://westmichigancardiology.org/screening-packages',
    NULL,
    NULL,
    '616-456-9553',
    '616-454-5371',
    'wmc.billing@wmcardiology.com',
    'Grand Rapids is the documented advanced screening hub; payment is due at screening and no insurance claim is filed.',
    NOW()
  ),
  (
    'Revere Health — Provo Cardiology',
    'Provo',
    'UT',
    '84604',
    '1055 North 500 West, Building C #201, Provo, UT 84604',
    206,
    'CPT 93015 Cardiovascular Stress Test',
    'CPT 93015 — Cardiovascular stress test — $206; provider defines physical stress as typically treadmill or bicycle',
    'Provider-posted uninsured procedure price; prompt-pay discount may apply',
    'A',
    'https://reverehealth.com/procedure-pricing/',
    NULL,
    NULL,
    '(801) 373-4366',
    NULL,
    'patientconcerns@reverehealth.com',
    'Procedure price is practice-wide; Provo Cardiology is explicitly listed as an Exercise Treadmill performing location.',
    NOW()
  ),
  (
    'Antonio Rosado, M.D. Clinical and Interventional Cardiology',
    'Miami Beach',
    'FL',
    '33140',
    '4302 Alton Road, Suite 470, Miami Beach, FL 33140',
    250,
    'Exercise Stress Test (Plain Treadmill)',
    'Self-pay Exercise stress test (plain treadmill) — $250; nuclear imaging and stress echocardiogram are priced separately',
    'Self-pay; in-office cardiac testing',
    'A',
    'https://www.drrosadocardiologist.com/fix',
    NULL,
    NULL,
    '786-709-5865',
    '305-397-8889',
    NULL,
    'Active Miami Beach cardiology practice with direct self-pay pricing.',
    NOW()
  ),
  (
    'Harvard Cardiovascular',
    'Philadelphia',
    'PA',
    '19107',
    '235 N Broad St, 3rd Floor, Philadelphia, PA 19107',
    275,
    'Exercise Stress Test',
    'Exercise Stress Test — $275; treadmill with EKG; testing, interpretation and report included',
    'Self-pay; new patient consultation required',
    'A',
    'https://harvardcardiovascular.com/product/exercise-stress-test/',
    NULL,
    NULL,
    '610-332-9207',
    '215-604-7954',
    'pm@harvardcardiovascular.com',
    'Pricing is practice-wide; Philadelphia is used conservatively for the location-specific registry row.',
    NOW()
  ),
  (
    'Cleveland Clinic Executive Health',
    'Cleveland',
    'OH',
    '44195',
    '9500 Euclid Avenue, Cleveland, OH 44195',
    860,
    'Exercise Stress Test',
    'Cleveland Clinic Executive Health self-pay fee schedule lists Exercise stress test — $860',
    'Executive Health self-pay; discounted for self-payors and not billable to insurance; dependent upon age and/or risk factors',
    'A-',
    'https://my.clevelandclinic.org/-/scassets/files/org/wellness/executive-health/2024-self-pay-fee-schedule',
    NULL,
    NULL,
    '216-444-5707',
    NULL,
    'exechealth@ccf.org',
    'Cleveland Clinic Main Campus Executive Health. The provider-hosted self-pay schedule remains live and lists the exercise stress test at $860; the document is labeled 2024, so source year is preserved in this note.',
    NOW()
  ),
  (
    'Cutchins Cardiovascular Medicine',
    'New York',
    'NY',
    '10022',
    '30 E 60th St, Suite 1205, New York, NY 10022',
    1250,
    'Exercise Treadmill Test',
    'Exercise Treadmill Test — $1,250; evaluates ischemic heart disease, heart-rate response and exercise tolerance',
    'Direct-pay practice; does not accept insurance',
    'A',
    'https://cutchinscvm.com/pricing-1',
    NULL,
    NULL,
    '212-599-3029',
    '212-904-0979',
    'scheduling@cutchinscvm.com',
    'Current NYC cardiovascular clinic; in-office treadmill testing and direct-pay pricing are both confirmed.',
    NOW()
  )
ON CONFLICT (provider, city, state, zip, service, price)
DO UPDATE SET
  address = EXCLUDED.address,
  match_text = EXCLUDED.match_text,
  access = EXCLUDED.access,
  tier = EXCLUDED.tier,
  source_url = EXCLUDED.source_url,
  latitude = COALESCE(EXCLUDED.latitude, stress_test_locations.latitude),
  longitude = COALESCE(EXCLUDED.longitude, stress_test_locations.longitude),
  phone = EXCLUDED.phone,
  fax = EXCLUDED.fax,
  email = EXCLUDED.email,
  footprint_note = EXCLUDED.footprint_note,
  updated_at = NOW();
