INSERT INTO stress_test_locations (
  provider, city, state, zip, address, price, service, match_text,
  access, tier, source_url, latitude, longitude, phone, fax, email,
  footprint_note, updated_at
)
VALUES
  (
    'Independent Physicians Medical Center (IPMC)',
    'Philadelphia',
    'PA',
    '19115',
    '9908 E Roosevelt Blvd, Philadelphia, PA 19115',
    150,
    'Stress EKG / Standard Exercise Stress Test (ECG only)',
    'Self-pay page lists Stress Echo / Stress EKG — $500 / $150; current 2026 provider article defines its standard stress test as ECG-only monitoring during exercise with no imaging',
    'Self-pay; outpatient cardiology testing',
    'A',
    'https://ipmcmed.com/self-pay/',
    NULL,
    NULL,
    '215-464-3300',
    '215-464-0805',
    'reports@ipmcmed.com',
    'Current IPMC self-pay page publishes Stress EKG at $150. A March 16, 2026 provider article separately defines the standard stress test as ECG-only testing during exercise and confirms standard stress testing is offered at the Northeast Philadelphia center.',
    NOW()
  ),
  (
    'Houston Family Physicians PA',
    'Houston',
    'TX',
    '77074',
    '8313 Southwest Freeway, Suite 105, Houston, TX 77074',
    195,
    'Stress EKG / Exercise Stress Test',
    'Direct provider cash-price page lists Cardio stress test $195 and Stress EKG $195; current provider site lists Exercise Stress Test among its in-house comprehensive diagnostic testing services',
    'Cash/self-pay; provider states it accepts self-pay and cash',
    'A',
    'https://www.houstonfamilyphysicians.com/cash-price-for-ultrasound.html',
    NULL,
    NULL,
    '281-704-3836',
    '713-588-8600',
    NULL,
    'The direct cash-price page names this location and the Kirby Drive location for the $195 stress testing. The current Houston Family Physicians site continues to list this office and explicitly lists Exercise Stress Test as an in-house diagnostic service.',
    NOW()
  ),
  (
    'Houston Family Physicians PA',
    'Houston',
    'TX',
    '77054',
    '8968 Kirby Drive, Houston, TX 77054',
    195,
    'Stress EKG / Exercise Stress Test',
    'Direct provider cash-price page lists Cardio stress test $195 and Stress EKG $195; current provider site lists Exercise Stress Test among its in-house comprehensive diagnostic testing services',
    'Cash/self-pay; provider states it accepts self-pay and cash',
    'A',
    'https://www.houstonfamilyphysicians.com/cash-price-for-ultrasound.html',
    NULL,
    NULL,
    '281-704-3836',
    '713-588-8600',
    NULL,
    'The direct cash-price page names this location and the Southwest Freeway location for the $195 stress testing. The current Houston Family Physicians site continues to list this office and explicitly lists Exercise Stress Test as an in-house diagnostic service.',
    NOW()
  )
ON CONFLICT (provider, city, state, zip, service, price)
DO UPDATE SET
  address = EXCLUDED.address,
  match_text = EXCLUDED.match_text,
  access = EXCLUDED.access,
  tier = EXCLUDED.tier,
  source_url = EXCLUDED.source_url,
  latitude = COALESCE(EXCLUDED.latitude, stress_test_locations.latitude),
  longitude = COALESCE(EXCLUDED.longitude, stress_test_locations.longitude),
  phone = EXCLUDED.phone,
  fax = EXCLUDED.fax,
  email = EXCLUDED.email,
  footprint_note = EXCLUDED.footprint_note,
  updated_at = NOW();
