INSERT INTO stress_test_locations (
  provider, city, state, zip, address, price, service, match_text,
  access, tier, source_url, latitude, longitude, phone, fax, email,
  footprint_note, updated_at
)
VALUES
  (
    'Independent Physicians Medical Center (IPMC)',
    'Philadelphia',
    'PA',
    '19115',
    '9908 Roosevelt Blvd, Philadelphia, PA 19115',
    150,
    'Stress EKG',
    'Stress Echo / Stress EKG — $500 / $150',
    'Self-pay; prescription required for diagnostic testing',
    'Direct provider self-pay price',
    'https://ipmcmed.com/self-pay/',
    NULL,
    NULL,
    '215-464-3300',
    '215-464-0805',
    'reports@ipmcmed.com',
    'Independent outpatient medical center with cardiology, imaging, and clinic services under one roof.',
    NOW()
  ),
  (
    'Telluride Regional Medical Center',
    'Telluride',
    'CO',
    '81435',
    '500 West Pacific Ave, Telluride, CO 81435',
    88,
    'CPT 93015 Cardiovascular Stress Test',
    '93015 — Cardiovascular stress test using treadmill/bicycle exercise — Self Pay Fee $88',
    'Self-pay fee published in active May 2025 fee schedule',
    'Direct provider fee schedule',
    'https://www.tellmed.org/files/65f2aa6dd/Fee%2BSchedule-%2BActive_May%2B2025.pdf',
    NULL,
    NULL,
    '970-728-3848',
    '970-728-3404',
    NULL,
    'Telluride Regional Medical Center main clinic; provider fee schedule explicitly labels the allowed amount as the Self Pay Fee.',
    NOW()
  ),
  (
    'NSC Cardiology',
    'Johns Creek',
    'GA',
    '30024',
    '5400 Laurel Springs Parkway, Suite 1401, Johns Creek, GA 30024',
    200,
    'Exercise Treadmill Test (ETT)',
    '2025 Self-Pay Rates: Exercise Treadmill Test (ETT) $200; December 2025 newsletter states SELF PAY RATES UNCHANGED FOR 2026',
    'Self-pay; payment in full required prior to testing',
    'Direct provider self-pay PDF confirmed current for 2026',
    'https://heartdrsingh.com/wp-content/uploads/2024/12/NSC-Cardiology-Self-Pay-Rates-2025.pdf',
    NULL,
    NULL,
    '678-208-0165',
    '888-814-0852',
    'DrSingh@nsccardiology.com',
    'NSC Cardiology Johns Creek office. Practice newsletter published in 2026 states 2025 self-pay rates are unchanged for 2026.',
    NOW()
  ),
  (
    'NSC Cardiology',
    'Cumming',
    'GA',
    '30041',
    '1100 Northside Forsyth Drive, Suite 345, Cumming, GA 30041',
    200,
    'Exercise Treadmill Test (ETT)',
    '2025 Self-Pay Rates: Exercise Treadmill Test (ETT) $200; December 2025 newsletter states SELF PAY RATES UNCHANGED FOR 2026',
    'Self-pay; payment in full required prior to testing',
    'Direct provider self-pay PDF confirmed current for 2026',
    'https://heartdrsingh.com/wp-content/uploads/2024/12/NSC-Cardiology-Self-Pay-Rates-2025.pdf',
    NULL,
    NULL,
    '678-845-8960',
    '888-814-0852',
    'DrSingh@nsccardiology.com',
    'NSC Cardiology Cumming office. Practice newsletter published in 2026 states 2025 self-pay rates are unchanged for 2026.',
    NOW()
  ),
  (
    'Advanced Heart and Vascular Center of New Mexico',
    'Carlsbad',
    'NM',
    '88220',
    '1619 Skyline Circle, Suite A, Carlsbad, NM 88220',
    300,
    'CPT 93015 Stress Test',
    'Procedure and Diagnostic Testing Self-Pay Rates as of 5/1/2025: CPT code 93015 - Stress Test - $300',
    'Self-pay diagnostic testing',
    'Direct provider self-pay PDF',
    'https://cdn.hibuwebsites.com/565d13e122ac443b92836a87dc5a04ab/files/uploaded/advanced-heart-and-vascular-center-of-new-mexico-self-pay-rates.pdf',
    NULL,
    NULL,
    '575-941-4400',
    '833-620-2406',
    'info@advancedheartnm.com',
    'Advanced Heart and Vascular Center of New Mexico; direct self-pay schedule dated May 1, 2025.',
    NOW()
  ),
  (
    'Cardiovascular Interventions, P.A.',
    'Orlando',
    'FL',
    '32803',
    '1900 North Mills Avenue, Orlando, FL 32803',
    140,
    'Regular Stress Test',
    'Direct self-pay Regular Stress Test — $140; provider stress-test lab page defines the regular stress test as treadmill walking until target heart rate',
    'Self-pay cash rate; in-office treadmill stress test',
    'Direct provider self-pay price',
    'https://orlandocvi.com/patient-resources/self-pay-rates-at-cvi/',
    NULL,
    NULL,
    '(407) 894-4880',
    '(407) 894-2364',
    NULL,
    'Current Orlando cardiovascular clinic. The live self-pay page lists Regular Stress Test at $140 and the practice stress-test lab page confirms it is treadmill exercise. The pricing table notes rates up to date as of 03-24.',
    NOW()
  ),
  (
    'Harvard Cardiovascular',
    'Philadelphia',
    'PA',
    '19107',
    '235 N Broad St, 3rd Floor, Philadelphia, PA 19107',
    275,
    'Exercise Stress Test',
    'Exercise Stress Test — $275; treadmill with EKG; testing, interpretation and report included',
    'Self-pay; new patient consultation required',
    'Direct provider self-pay price',
    'https://harvardcardiovascular.com/product/exercise-stress-test/',
    NULL,
    NULL,
    '610-332-9207',
    '215-604-7954',
    'pm@harvardcardiovascular.com',
    'Harvard Cardiovascular publishes four PA/NJ offices and offers in-person stress testing; exact testing site should be confirmed when booking. This row conservatively uses the Philadelphia office.',
    NOW()
  ),
  (
    'Antonio Rosado, M.D. Clinical and Interventional Cardiology',
    'Miami Beach',
    'FL',
    '33140',
    '4302 Alton Road, Suite 470, Miami Beach, FL 33140',
    250,
    'Exercise Stress Test (Plain Treadmill)',
    'Self-pay Exercise stress test (plain treadmill) — $250; nuclear imaging and stress echocardiogram are listed separately',
    'Self-pay; in-office cardiac testing',
    'Direct provider self-pay price',
    'https://www.drrosadocardiologist.com/fix',
    NULL,
    NULL,
    '786-709-5865',
    '305-397-8889',
    NULL,
    'Active Miami Beach cardiology practice. Current practice site states in-house cardiac testing and competitive pricing for patients without insurance.',
    NOW()
  ),
  (
    'Cutchins Cardiovascular Medicine',
    'New York',
    'NY',
    '10022',
    '30 E 60th St, Suite 1205, New York, NY 10022',
    1250,
    'Exercise Treadmill Test',
    'Exercise Treadmill Test — $1,250; evaluates ischemic heart disease, heart-rate response and exercise tolerance',
    'Direct-pay practice; does not accept insurance',
    'Direct provider posted price',
    'https://cutchinscvm.com/pricing-1',
    NULL,
    NULL,
    '212-599-3029',
    '212-904-0979',
    'scheduling@cutchinscvm.com',
    'Current NYC cardiovascular clinic. Provider FAQ explicitly states the practice does not accept insurance, and its diagnostic-services page confirms in-office treadmill testing.',
    NOW()
  ),
  (
    'West Michigan Cardiology',
    'Grand Rapids',
    'MI',
    '49525',
    '3210 Eagle Run Dr NE, Grand Rapids, MI 49525',
    150,
    'Treadmill EKG Stress Test',
    'Individual screening test: Treadmill EKG Stress Test — $150',
    'Cash-pay cardiovascular screening; no insurance claim, referral, or prior authorization required',
    'Direct provider cash-pay price',
    'https://westmichigancardiology.org/screening-packages',
    NULL,
    NULL,
    '616-456-9553',
    '616-454-5371',
    'wmc.billing@wmcardiology.com',
    'Current West Michigan Cardiology screening program. Grand Rapids is used conservatively as the documented screening/testing hub; payment is due at screening and the program states no insurance claim will be filed.',
    NOW()
  )
ON CONFLICT (provider, city, state, zip, service, price)
DO UPDATE SET
  address = EXCLUDED.address,
  match_text = EXCLUDED.match_text,
  access = EXCLUDED.access,
  tier = EXCLUDED.tier,
  source_url = EXCLUDED.source_url,
  latitude = COALESCE(EXCLUDED.latitude, stress_test_locations.latitude),
  longitude = COALESCE(EXCLUDED.longitude, stress_test_locations.longitude),
  phone = EXCLUDED.phone,
  fax = EXCLUDED.fax,
  email = EXCLUDED.email,
  footprint_note = EXCLUDED.footprint_note,
  updated_at = NOW();